#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u toshkoevoets --password-stdin;
docker push ${IMAGE_TAG}
docker tag ${IMAGE_TAG} toshkoevoets/${DOCKER_IMAGE_NAME}:${TRAVIS_TAG}
docker push toshkoevoets/${DOCKER_IMAGE_NAME}:${TRAVIS_TAG}
