#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
docker push ${IMAGE_TAG}
docker tag ${IMAGE_TAG} ${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:latest
docker push ${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:latest
